// <auto-generated />
using System;
using ForumAPI.DataContext;
using ForumAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ForumAPI.Migrations
{
    [DbContext(typeof(ForumContext))]
    partial class ForumContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "role", new[] { "ADMIN", "USER" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "role", "role", new[] { "USER", "ADMIN" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ForumAPI.Models.Category", b =>
                {
                    b.Property<long>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("CategoryId")
                        .HasName("category_pkey");

                    b.HasIndex(new[] { "Name" }, "name_uniq")
                        .IsUnique();

                    b.ToTable("category");
                });

            modelBuilder.Entity("ForumAPI.Models.Follow", b =>
                {
                    b.Property<long>("FollowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("follow_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FollowId"));

                    b.Property<long?>("FolloweeId")
                        .HasColumnType("bigint")
                        .HasColumnName("followee_id");

                    b.Property<long?>("FollowerId")
                        .HasColumnType("bigint")
                        .HasColumnName("follower_id");

                    b.HasKey("FollowId")
                        .HasName("follows_pkey");

                    b.HasIndex("FolloweeId");

                    b.HasIndex("FollowerId");

                    b.ToTable("follows");
                });

            modelBuilder.Entity("ForumAPI.Models.Forumlike", b =>
                {
                    b.Property<long>("LikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("like_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LikeId"));

                    b.Property<long?>("PostId")
                        .HasColumnType("bigint")
                        .HasColumnName("post_id");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("LikeId")
                        .HasName("forumlike_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("forumlike");
                });

            modelBuilder.Entity("ForumAPI.Models.Forumuser", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<byte[]>("Icon")
                        .HasColumnType("bytea")
                        .HasColumnName("icon");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("password");

                    b.Property<Role>("Role")
                        .HasColumnType("role")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("forumuser_pkey");

                    b.HasIndex(new[] { "Email" }, "email_uniq")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "username_uniq")
                        .IsUnique();

                    b.ToTable("forumuser");
                });

            modelBuilder.Entity("ForumAPI.Models.Post", b =>
                {
                    b.Property<long>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("post_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PostId"));

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<long?>("ParentPostId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_post_id");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("PostId")
                        .HasName("post_pkey");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ParentPostId");

                    b.HasIndex("UserId");

                    b.ToTable("post");
                });

            modelBuilder.Entity("ForumAPI.Models.Postimage", b =>
                {
                    b.Property<long>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("image_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ImageId"));

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea")
                        .HasColumnName("image");

                    b.Property<long?>("PostId")
                        .HasColumnType("bigint")
                        .HasColumnName("post_id");

                    b.HasKey("ImageId")
                        .HasName("postimage_pkey");

                    b.HasIndex("PostId");

                    b.ToTable("postimage");
                });

            modelBuilder.Entity("ForumAPI.Models.Refreshtoken", b =>
                {
                    b.Property<long>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("token_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TokenId"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expiry_date");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId")
                        .HasName("refreshtoken_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("refreshtoken");
                });

            modelBuilder.Entity("ForumAPI.Models.Follow", b =>
                {
                    b.HasOne("ForumAPI.Models.Forumuser", "Followee")
                        .WithMany("FollowFollowees")
                        .HasForeignKey("FolloweeId")
                        .HasConstraintName("follows_followee_id_fkey");

                    b.HasOne("ForumAPI.Models.Forumuser", "Follower")
                        .WithMany("FollowFollowers")
                        .HasForeignKey("FollowerId")
                        .HasConstraintName("follows_follower_id_fkey");

                    b.Navigation("Followee");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("ForumAPI.Models.Forumlike", b =>
                {
                    b.HasOne("ForumAPI.Models.Forumuser", "User")
                        .WithMany("Forumlikes")
                        .HasForeignKey("UserId")
                        .HasConstraintName("forumlike_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForumAPI.Models.Post", b =>
                {
                    b.HasOne("ForumAPI.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("post_category_id_fkey");

                    b.HasOne("ForumAPI.Models.Post", "ParentPost")
                        .WithMany("InverseParentPost")
                        .HasForeignKey("ParentPostId")
                        .HasConstraintName("post_parent_post_id_fkey");

                    b.HasOne("ForumAPI.Models.Forumuser", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("post_user_id_fkey");

                    b.Navigation("Category");

                    b.Navigation("ParentPost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForumAPI.Models.Postimage", b =>
                {
                    b.HasOne("ForumAPI.Models.Post", "Post")
                        .WithMany("Postimages")
                        .HasForeignKey("PostId")
                        .HasConstraintName("postimage_post_id_fkey");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("ForumAPI.Models.Refreshtoken", b =>
                {
                    b.HasOne("ForumAPI.Models.Forumuser", "User")
                        .WithMany("Refreshtokens")
                        .HasForeignKey("UserId")
                        .HasConstraintName("refreshtoken_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForumAPI.Models.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("ForumAPI.Models.Forumuser", b =>
                {
                    b.Navigation("FollowFollowees");

                    b.Navigation("FollowFollowers");

                    b.Navigation("Forumlikes");

                    b.Navigation("Posts");

                    b.Navigation("Refreshtokens");
                });

            modelBuilder.Entity("ForumAPI.Models.Post", b =>
                {
                    b.Navigation("InverseParentPost");

                    b.Navigation("Postimages");
                });
#pragma warning restore 612, 618
        }
    }
}
