name: Backend validation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        working-directory: /Backend/ForumAPI/ForumAPI
        run: dotnet restore ForumAPI.csproj

      - name: Build
        working-directory: /Backend/ForumAPI/ForumAPI
        run: dotnet build ForumAPI.csproj --no-restore

      - name: Test
        working-directory: /Backend/ForumAPI/ForumAPI
        run: dotnet test ForumAPI.csproj --no-build --verbosity normal