name: Backend validation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend/ForumAPI

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore ForumAPI/ForumAPI.csproj

      - name: Build
        run: dotnet build ForumAPI/ForumAPI.csproj --no-restore

      - name: Test
        run: dotnet test ForumAPI/UnitTests/UnitTests.csproj --no-build --verbosity normal
